### ISSUE TITLE
[1.18.1] Neither experience (from mining coal, lapiz or similar) nor multiple raw copper drop from More Ore Stone's blocks

### ISSUE THREAD

**Issue by GeorgeOrwell1** [AstralOrdana/Mores-Forge#7]

**Comment by AstralOrdana** [comment]
please specify which version of the mod you are using

**Comment by GeorgeOrwell1** [comment]
> please specify which version of the mod you are using

I'm using version 1.3.0.

**Comment by AstralOrdana** [comment]
I just tested this in game and everything drops as it should, maybe you're using the wrong tier of pickaxe.

**Comment by GeorgeOrwell1** [comment]
Sorry, I was using the 1.2.0 version. I noticed that multiple raw copper _do_ drop from More Ore Stone's ore variants (I was just unlucky in survival as I always only got one lol), but it still seems that coal and lapiz variants from your mod don't drop experience (see video for proof).

https://user-images.githubusercontent.com/72312697/158352618-fca06301-5320-490e-ac3f-b1df8b72d1f1.mp4
